urls.py
from django.conf.urls.defaults import patterns, include, url
from webblog.views import *

# Uncomment the next two lines to enable the admin:'blog.views.home', name='home'
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
     url(r'^index/post=(?P<postnumber>\d+)[/]?$',index),
     url(r'^index.*$', redirect_index),
     url(r'^login[/]?$', login),
     url(r'^register[/]?$', register),
     url(r'^blogpost/new[/]?$', create_blogpost),
     url(r'^blogpost/edit/id=(?P<postid>\d+)[/]?$', edit_blogpost),
     url(r'^blogpost/delete/id=(?P<postid>\d+)[/]?$', delete_blogpost),
     url(r'^blogpost/detail/id=(?P<postid>\d+)[/]?$', detail_blogpost),
     url(r'^logout/$', logout)
    # url(r'^blog/', include('blog.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

webblog/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User, related_name="%(class)s_author")
    content = models.CharField(max_length=10000)
    publication_date = models.DateTimeField()
    likes = models.ManyToManyField(User, related_name="%(class)s_likes")


    class Meta:
        abstract = True
        ordering = ['-publication_date']



class Blogpost(Post):
    title = models.CharField(max_length=1000)
    tags = models.CharField(max_length=500)


class Comment(Post):
    blogpost = models.ForeignKey(Blogpost)

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    birthday = models.DateField()
    gender = models.SmallIntegerField(max_length=1);

webblog/forms.py
__author__ = 'stephan'

from django import forms

class LoginForm(forms.Form):
    user_name = forms.CharField(max_length=30, label='Name')
    user_password = forms.CharField(label ='Password', widget=forms.PasswordInput(render_value=False))

class BlogpostCreationForm(forms.Form):
    post_title = forms.CharField(label='Titel', max_length=1000)
    post_content = forms.CharField(label='', max_length=10000, widget=forms.Textarea)
    post_tags = forms.CharField(label='Tags', max_length=500)

    def clean_post_content(self):
        post_content = self.cleaned_data['post_content']
        words = post_content.split()
        for word in words:
            if len(word) > 140:
                raise forms.ValidationError('No words with more than 140 characters.')
        return post_content

webblog/views.py
# Create your views here.
import datetime
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from webblog.models import *
from webblog.forms import *

MESSAGES = {'edit_success'     : 'Blogpost erfolgreich editiert.',
            'delete_success'   : 'Blogpost erfolgreich geloescht.',
            'create_success'   : 'Blogpost erfolgreich erstellt',
            'login_success'    : 'Erfolgreich eingeloggt.',
            'register_sccuess' : 'Benutzer erfolgreich erstellt.',
            'logout_success'   : 'Erfolgreich ausgeloggt'}

def index(request, postnumber = 1):
    postnumber = int(postnumber)
    postnumber -= 1                                                                                                 #postnr zu listindex
    blogposts = Blogpost.objects.all()
    blogposts =  blogposts if postnumber in range(0,len(blogposts)) else []                                            #ersten Index pruefen
    if blogposts:
        showposts = blogposts[postnumber:(postnumber+15 if postnumber+15 <= len(blogposts) else len(blogposts))]    #zweiten Index pruefen
    else:
        showposts = []                                                                                              #keine Posts unter postnr
    likes = {}
    for i in range(0,len(showposts)-1):
        likes[showposts[i].pk] = len(showposts[i].likes.all())
    return render_to_response('index.html',{'blogposts' : showposts, 'message' : MESSAGES.get(request.GET.get('msg',''),''),
                              'likes' : likes}, context_instance=RequestContext(request))

def redirect_index(request):
    return HttpResponseRedirect('/index/post=1')

def login(request):
    errors = []
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user_name = form.cleaned_data['user_name']
            user_password = form.cleaned_data['user_password']
            user = auth.authenticate(username=user_name,password=user_password)
            if user != None and user.is_active:
                auth.login(request,user)

                return HttpResponseRedirect(request.GET.get('next','/index/post=1/?msg=login_success'))
            else:
                errors.append('Benutzer oder Password nicht bekannt.')
        return render_to_response('user/login.html', {'form' : form, 'errors' : errors}, context_instance=RequestContext(request))

    else:
        form = LoginForm()
        return render_to_response('user/login.html', {'form' : form, 'errors' : errors}, context_instance=RequestContext(request))

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            user_name = form.cleaned_data['username']
            user_password = form.cleaned_data['password1']
            user = auth.authenticate(username=user_name,password=user_password)
            auth.login(request,user)
            return HttpResponseRedirect(request.GET.get('next','/index/post=1/?msg=register_sccuess'))
        else:
            return render_to_response('user/register.html', {'form' : form},context_instance=RequestContext(request))
    else:
        form = UserCreationForm()
        return render_to_response('user/register.html', {'form' : form},context_instance=RequestContext(request))

@login_required()
def create_blogpost(request):
    if request.method == 'POST':
        form = BlogpostCreationForm(request.POST)
        if form.is_valid():
            blogpost = Blogpost(author = request.user,
                                content = form.cleaned_data['post_content'],
                                publication_date = datetime.datetime.now(),
                                title = form.cleaned_data['post_title'],
                                tags = form.cleaned_data['post_tags'])
            blogpost.save()
            return HttpResponseRedirect('/index/post=1/?msg=%s' % 'create_success')
        else:
            return render_to_response('post/create_blogpost.html', {'form' : form},context_instance=RequestContext(request))
    else:
        form = BlogpostCreationForm()
        return render_to_response('post/create_blogpost.html', {'form' : form},context_instance=RequestContext(request))

@login_required()
def edit_blogpost(request, postid):
    post = Blogpost.objects.get(pk=postid)

    if post == None:
        raise Http404

    if not edit_delete_permission(request, post):
        return HttpResponse('403 Forbidden')

    if request.method == 'POST':
        form = BlogpostCreationForm(request.POST)
        if form.is_valid():
            post.title = form.cleaned_data['post_title']
            post.content = form.cleaned_data['post_content']
            post.tags = form.cleaned_data['post_tags']
            post.save()
            return HttpResponseRedirect('/blogpost/detail/id=%s/?msg=%s' % (postid, 'edit_success'))
        else:
            return render_to_response('post/edit_blogpost.html', {'form' : form},context_instance=RequestContext(request))
    else:
        form = BlogpostCreationForm(initial={'post_title' : post.title, 'post_content' : post.content, 'post_tags' : post.tags})
        return render_to_response('post/edit_blogpost.html', {'form' : form},context_instance=RequestContext(request))


@login_required()
def delete_blogpost(request, postid):
    post = Blogpost.objects.get(pk=postid)

    if post == None:
        raise Http404

    if not edit_delete_permission(request, post):
        return HttpResponse('403 Forbidden')

    if request.method == 'POST':
        if 'delete_confirm' in request.POST:
            post.delete()
            return HttpResponseRedirect('/index/post=1/?msg=%s' % 'delete_success')

        else:
            return HttpResponseRedirect('/index/post=1')
    else:
        return render_to_response('post/delete_blogpost.html', {'blogpost':post},context_instance=RequestContext(request))


@login_required()
def detail_blogpost(request, postid):
    post = Blogpost.objects.get(pk=postid)

    if post == None:
        raise Http404

    comments = Comment.objects.all().filter(blogpost = post)


    return render_to_response('post/detail_blogpost.html', {'blogpost' : post,
                                                            'comments' : comments,
                                                            'message' : MESSAGES.get(request.GET.get('msg',''),'')},
                                                             context_instance=RequestContext(request))

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/index/post=1/?msg=%s' % 'logout_success')


def edit_delete_permission(request, post):
    if not (request.user == post.author or request.user.is_superuser == 1):
        return False
    else:
        return True

webblog/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Weblog</title>

    <style type="text/css">


        #blogtitle {
            text-align: center;
            color: black;
            width: auto;
            height: auto;
        }

        #content {
            text-align: center;
        }

        .blogpost {
            margin-left: 15%;
            margin-right: 15%;
            margin-bottom: 1em;
            border: 1px solid black;
            text-align: center;
        }

        .blogpost .header {
            border-bottom: 1px solid black;
            width: 100%;
        }

        .blogpost .header .title {
            text-align: left;
            margin: 0;
            padding: 0;
            margin-left: 0.8em;
        }

        .blogpost .header table {
            width: 100%;
        }

        .blogpost .editlist {
            text-align: right;
            margin-right: 0.5em;
        }

        .blogpost .editlist li {
            margin: 0;
            padding: 0;
            list-style: none;
            display: inline;
        }

        .blogpost .content {
            text-align: left;
            margin: 0.8em;
        }

        .blogpost .footer {
            margin: 0;
            padding: 0.8em;
            border-top: 1px solid black;
            background-color: silver;
            width: 100%
        }

        .blogpost .footer .author {
            text-align: center;
            width: 33%;
        }

        .blogpost .footer .publication_date {
            text-align: center;
            width: 33%;
        }

        .blogpost .footer .likes {
            text-align: center;
            width: 33%;
        }

        .form_table {
            margin-left: auto;
            margin-right: auto;
        }

        .form_table ul {
            margin: 0;
            padding: 0;

        }

        .form_table ul li {
            margin: 0;
            padding: 0;
            list-style: none;
            color: red;
        }

        .form_table_container {
            text-align: center;
        }

        .confirm_button_td {
            text-align: left;
        }

        .message {
            margin-left: 15%;
            margin-right: 15%;
            border: 2px solid green;
            background-color: #adff2f;
            text-align: center;
        }

        #topbar {
            background-color: silver;
            margin: 0;
            width: 100%;
        }

        #topbar li {
            list-style: none;
            display: inline;
            margin: 0;
            padding: 0;
            margin-left: 2.5%;
            background-color: silver;
        }

        #topbar li a {
            margin: 0;
            padding: 0;
            text-decoration: none;
            color: black;
        }

        #topbar li:hover {
            background-color: lightgray;
        }

        #id_post_content {
            height: 25em;
            width: 45em;
        }


    </style>
    <link href="{{ STATIC_URL }}bootstrap.css" rel="stylesheet"/>
    <link href="{{ STATIC_URL }}bootstrap.min.css" rel="stylesheet"/>
    <style>
        .table-condensed td {
            text-align: center;
        }

        .table-condensed  {
            width: auto;
            height: auto;
            margin: auto;
        }
    </style>
    <!--<script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.min.js"></script>//-->

</head>

<body>
{% block header %}
<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            {% if user.is_authenticated %}
            <ul class="nav">
                <li><a class="brand" href="">Eingeloggt als {{user.username}}</a></li>
                <li class="divider-vertical"></li>
                <li><a href='/blogpost/new/'>Blogpost erstellen</a></li>
            </ul>
            <ul class="nav pull-right">
                <li><a href='/logout/'>Logout</a></li>
            </ul>
            {% else %}
            <ul class="nav">
                <li><a href='/login/'>Login</a></li>
                <li><a href='/register/'>Registrieren</a></li>
            </ul>
            {% endif %}
        </div>
    </div>
</div>

{% if message %}
    <p class = 'message'>{{message}}</p>
{% endif %}
<!--
<ul id = 'topbar'>
    {% if user.is_authenticated %}
        <li>Eingeloggt als {{user.username}}</li>
        <li><a href = '/logout/'>Logout</a></li>
        <li><a href = '/blogpost/new/'>Blogpost erstellen</a></li>
    {% else %}
        <li><a href = '/login/'>Login</a></li>
        <li><a href = '/register/'>Registrieren</a></li>
    {% endif %}
</ul>
<a href = '/index/post=1/'><h1 id = "blogtitle">Unser Weblog</h1></a>

//-->
{% endblock %}

<div id="content">
    {% block content %}
    <p>Sample-Content-Paragraph</p>
    {% endblock %}
</div>
</body>
</html>

webblog/templates/index.html
{% extends "base.html" %}

{% block content %}
    {% load post_extras %}
    {% load markup %}
    {% if blogposts %}
        {%for blogpost in blogposts%}
            <div class = "blogpost">
                <div class = "header">
                    <table><tr>
                        <td><a href = '/blogpost/detail/id={{blogpost.pk}}'><h2 class = "title">{{blogpost.title}}</h2></a></td>
                        {% if user.is_authenticated %}
                            {% if user == blogpost.author or user.is_superuser %}
                                <td><ul class = "editlist">
                                    <li><a href = "/blogpost/edit/id={{blogpost.pk}}">Edit</a></li>
                                    <li><a href = "/blogpost/delete/id={{blogpost.pk}}">Delete</a></li>
                                </ul></td>
                            {% endif %}
                        {% endif %}
                    </tr></table>
                </div>

                <p class = "content">{{blogpost.content|markdown}}</p>
                <table class = "footer">
                    <tr><td class = 'author'>Author: {{blogpost.author}}</td>
                    <td class = 'publication_date'>{{blogpost.publication_date}}</td>
                    <td class = 'likes'>{{blogpost|likes}} Like{{blogpost|likes|pluralize}}
                                        <img src = '{{ STATIC_URL }}img/like.jpg' alt = 'I LIKE' onclick=''> </td> </tr>
                </table>
            </div>
        {%endfor%}
    {% else %}
        <h2>Es sind auf dieser Seite leider keine Blogposts vorhanden :(</h2>
    {% endif %}

{% endblock %}